site_name: Collections Ontology VIVO Alignment
site_description: This document is part of the vivo ontology project entity extension development process
site_author: Rolf Guescini
docs_dir: docs/
repo_name: guescinr/collections-ontology
repo_url: https://github.com/guescinr/collections-ontology
nav:
  - COLLECTION VIVO ALIGNMENT ONTOLOGY: index.md
  - COMPETENCY QUESTIONS: cq.md
theme:
  name: material